let data = {
    AlamedaCounty: {
        "Violent_sum": 84241,
        "Homicide_sum": 146,
        "Rape_sum":7918,
        "Robbery_sum":4575,
        "AggAssault_sum": 5149,
        "PropertyCrime_sum": 61156,
        "Burglary_sum": 14273,
        "VehicleTheft_sum": 15516,
        "LarcenyTheft_sum":39699,
        "Arson_sum":486,
    },

    AlpineCounty: {
        "Violent_sum": 19,
        "Homicide_sum": 0,
        "Rape_sum":0,
        "Robbery_sum":0,
        "AggAssault_sum": 17,
        "PropertyCrime_sum": 23,
        "Burglary_sum": 19,
        "VehicleTheft_sum": 1,
        "LarcenyTheft_sum":14,
        "Arson_sum":0,
    },

    AmadorCounty: {
        "Violent_sum": 135,
        "Homicide_sum": 4,
        "Rape_sum":23,
        "Robbery_sum":13,
        "AggAssault_sum": 109,
        "PropertyCrime_sum": 716,
        "Burglary_sum": 312,
        "VehicleTheft_sum": 77,
        "LarcenyTheft_sum":506,
        "Arson_sum":3,
    },

    ButteCounty: {
        "Violent_sum": 1110,
        "Homicide_sum": 13,
        "Rape_sum":178,
        "Robbery_sum":120,
        "AggAssault_sum": 826,
        "PropertyCrime_sum": 4785,
        "Burglary_sum": 1925,
        "VehicleTheft_sum": 916,
        "LarcenyTheft_sum":3051,
        "Arson_sum":80,
    },

    CalaverasCounty: {
        "Violent_sum": 185,
        "Homicide_sum": 2,
        "Rape_sum":6,
        "Robbery_sum":4,
        "AggAssault_sum": 144,
        "PropertyCrime_sum": 677,
        "Burglary_sum": 441,
        "VehicleTheft_sum": 109,
        "LarcenyTheft_sum":385,
        "Arson_sum":0,
    },

    ColusaCounty: {
        "Violent_sum": 55,
        "Homicide_sum": 0,
        "Rape_sum":20,
        "Robbery_sum":11,
        "AggAssault_sum": 35,
        "PropertyCrime_sum": 316,
        "Burglary_sum": 188,
        "VehicleTheft_sum": 52,
        "LarcenyTheft_sum":189,
        "Arson_sum":3,
    },

    ContraCostaCounty: {
        "Violent_sum": 4002,
        "Homicide_sum": 50,
        "Rape_sum":1638,
        "Robbery_sum":1004,
        "AggAssault_sum": 2635,
        "PropertyCrime_sum": 22571,
        "Burglary_sum": 6815,
        "VehicleTheft_sum": 4323,
        "LarcenyTheft_sum":15512,
        "Arson_sum":232,
    },

    DelNorteCounty: {
        "Violent_sum": 230,
        "Homicide_sum": 1,
        "Rape_sum":50,
        "Robbery_sum":33,
        "AggAssault_sum": 152,
        "PropertyCrime_sum": 570,
        "Burglary_sum": 469,
        "VehicleTheft_sum": 93,
        "LarcenyTheft_sum":312,
        "Arson_sum":19,
    },

    ElDoradoCounty: {
        "Violent_sum": 531,
        "Homicide_sum": 6,
        "Rape_sum":59,
        "Robbery_sum":43,
        "AggAssault_sum": 384,
        "PropertyCrime_sum": 2318,
        "Burglary_sum": 1232,
        "VehicleTheft_sum": 167,
        "LarcenyTheft_sum":1644,
        "Arson_sum":12,
    },

    FresnoCounty: {
        "Violent_sum": 7405,
        "Homicide_sum": 87,
        "Rape_sum":1688,
        "Robbery_sum":1070,
        "AggAssault_sum": 5842,
        "PropertyCrime_sum": 25108,
        "Burglary_sum": 15676,
        "VehicleTheft_sum": 4994,
        "LarcenyTheft_sum":14177,
        "Arson_sum":183,
    },

    GlennCounty: {
        "Violent_sum": 115,
        "Homicide_sum": 0,
        "Rape_sum":10,
        "Robbery_sum":6,
        "AggAssault_sum": 94,
        "PropertyCrime_sum": 352,
        "Burglary_sum": 198,
        "VehicleTheft_sum": 70,
        "LarcenyTheft_sum":205,
        "Arson_sum":12,
    },

    HumboldtCounty: {
        "Violent_sum": 670,
        "Homicide_sum": 8,
        "Rape_sum":288,
        "Robbery_sum":141,
        "AggAssault_sum": 430,
        "PropertyCrime_sum": 3783,
        "Burglary_sum": 2282,
        "VehicleTheft_sum": 708,
        "LarcenyTheft_sum":2180,
        "Arson_sum":69,
    },

    ImperialCounty: {
        "Violent_sum": 560,
        "Homicide_sum": 14,
        "Rape_sum":126,
        "Robbery_sum":87,
        "AggAssault_sum": 436,
        "PropertyCrime_sum": 3208,
        "Burglary_sum": 2231,
        "VehicleTheft_sum": 538,
        "LarcenyTheft_sum":1809,
        "Arson_sum":131,
    },

    InyoCounty: {
        "Violent_sum": 121,
        "Homicide_sum": 0,
        "Rape_sum":31,
        "Robbery_sum":19,
        "AggAssault_sum": 91,
        "PropertyCrime_sum": 334,
        "Burglary_sum": 194,
        "VehicleTheft_sum": 51,
        "LarcenyTheft_sum":203,
        "Arson_sum":5,
    },

    KernCounty: {
        "Violent_sum": 6718,
        "Homicide_sum": 124,
        "Rape_sum":1999,
        "Robbery_sum":1249,
        "AggAssault_sum": 4990,
        "PropertyCrime_sum": 29208,
        "Burglary_sum": 13005,
        "VehicleTheft_sum": 8843,
        "LarcenyTheft_sum":14858,
        "Arson_sum":468,
    },

    KingsCounty: {
        "Violent_sum": 686,
        "Homicide_sum": 11,
        "Rape_sum":110,
        "Robbery_sum":79,
        "AggAssault_sum": 517,
        "PropertyCrime_sum": 2324,
        "Burglary_sum": 1019,
        "VehicleTheft_sum": 517,
        "LarcenyTheft_sum":1365,
        "Arson_sum":14,
    },

    LakeCounty: {
        "Violent_sum": 393,
        "Homicide_sum": 5,
        "Rape_sum":68,
        "Robbery_sum":41,
        "AggAssault_sum": 295,
        "PropertyCrime_sum": 1188,
        "Burglary_sum": 788,
        "VehicleTheft_sum": 314,
        "LarcenyTheft_sum":540,
        "Arson_sum":22,
    },

    LassenCounty: {
        "Violent_sum": 80,
        "Homicide_sum": 0,
        "Rape_sum":9,
        "Robbery_sum":6,
        "AggAssault_sum": 61,
        "PropertyCrime_sum": 379,
        "Burglary_sum": 254,
        "VehicleTheft_sum": 61,
        "LarcenyTheft_sum":211,
        "Arson_sum":4,
    },

    LosAngelesCounty: {
        "Violent_sum": 581777,
        "Homicide_sum": 841,
        "Rape_sum":26655,
        "Robbery_sum":15642,
        "AggAssault_sum": 37731,
        "PropertyCrime_sum": 18771,
        "Burglary_sum": 88031,
        "VehicleTheft_sum": 58224,
        "LarcenyTheft_sum":133660,
        "Arson_sum":4810,
    },

    MaderaCounty: {
        "Violent_sum": 1022,
        "Homicide_sum": 5,
        "Rape_sum":93,
        "Robbery_sum":55,
        "AggAssault_sum": 844,
        "PropertyCrime_sum": 3344,
        "Burglary_sum": 1042,
        "VehicleTheft_sum": 509,
        "LarcenyTheft_sum":1569,
        "Arson_sum":30,
    },

    MarinCounty: {
        "Violent_sum": 348,
        "Homicide_sum": 1,
        "Rape_sum":174,
        "Robbery_sum":99,
        "AggAssault_sum": 209,
        "PropertyCrime_sum": 3807,
        "Burglary_sum": 1246,
        "VehicleTheft_sum": 489,
        "LarcenyTheft_sum":2816,
        "Arson_sum":32,
    },
    MariposaCounty: {
        "Violent_sum": 80,
        "Homicide_sum": 5,
        "Rape_sum":2,
        "Robbery_sum":2,
        "AggAssault_sum": 63,
        "PropertyCrime_sum": 242,
        "Burglary_sum": 90,
        "VehicleTheft_sum": 16,
        "LarcenyTheft_sum":187,
        "Arson_sum":3,
    },
    MendocinoCounty: {
        "Violent_sum": 471,
        "Homicide_sum": 8,
        "Rape_sum":51,
        "Robbery_sum":33,
        "AggAssault_sum": 379,
        "PropertyCrime_sum": 1216,
        "Burglary_sum": 783,
        "VehicleTheft_sum": 178,
        "LarcenyTheft_sum":726,
        "Arson_sum":34,
    },
    MercedCounty: {
        "Violent_sum": 1833,
        "Homicide_sum": 27,
        "Rape_sum":378,
        "Robbery_sum":314,
        "AggAssault_sum": 1477,
        "PropertyCrime_sum": 7200,
        "Burglary_sum": 3251,
        "VehicleTheft_sum": 1466,
        "LarcenyTheft_sum":4330,
        "Arson_sum":191,
    },
    ModocCounty: {
        "Violent_sum": 13,
        "Homicide_sum": 0,
        "Rape_sum": 0,
        "Robbery_sum":0,
        "AggAssault_sum": 9,
        "PropertyCrime_sum": 56,
        "Burglary_sum": 31,
        "VehicleTheft_sum": 11,
        "LarcenyTheft_sum":20,
        "Arson_sum":3,
    },
    MonoCounty: {
        "Violent_sum": 33,
        "Homicide_sum": 1,
        "Rape_sum":2,
        "Robbery_sum":1,
        "AggAssault_sum": 24,
        "PropertyCrime_sum": 107,
        "Burglary_sum": 56,
        "VehicleTheft_sum": 12,
        "LarcenyTheft_sum":71,
        "Arson_sum":2,
    },

    MontereyCounty: {
        "Violent_sum": 2035,
        "Homicide_sum": 14,
        "Rape_sum":634,
        "Robbery_sum":381,
        "AggAssault_sum": 1433,
        "PropertyCrime_sum": 7124,
        "Burglary_sum": 3658,
        "VehicleTheft_sum": 1211,
        "LarcenyTheft_sum":4489,
        "Arson_sum":67,
    },
    NapaCounty: {
        "Violent_sum": 578,
        "Homicide_sum": 0,
        "Rape_sum":108,
        "Robbery_sum":66,
        "AggAssault_sum": 443,
        "PropertyCrime_sum": 1927,
        "Burglary_sum": 713,
        "VehicleTheft_sum": 244,
        "LarcenyTheft_sum":1397,
        "Arson_sum":12,
    },

    NevadaCounty: {
        "Violent_sum": 238,
        "Homicide_sum": 4,
        "Rape_sum":26,
        "Robbery_sum":18,
        "AggAssault_sum": 189,
        "PropertyCrime_sum": 881,
        "Burglary_sum": 590,
        "VehicleTheft_sum": 130,
        "LarcenyTheft_sum":514,
        "Arson_sum":8,
    },
    OrangeCounty: {
        "Violent_sum": 8144,
        "Homicide_sum": 71,
        "Rape_sum":3103,
        "Robbery_sum":1912,
        "AggAssault_sum": 5259,
        "PropertyCrime_sum": 58821,
        "Burglary_sum": 22152,
        "VehicleTheft_sum": 8480,
        "LarcenyTheft_sum":41251,
        "Arson_sum":360,
    },
    PlacerCounty: {
        "Violent_sum": 740,
        "Homicide_sum": 4,
        "Rape_sum":191,
        "Robbery_sum":126,
        "AggAssault_sum": 210,
        "PropertyCrime_sum": 5832,
        "Burglary_sum": 1949,
        "VehicleTheft_sum": 773,
        "LarcenyTheft_sum":4226,
        "Arson_sum":58,
    },
    PlumasCounty: {
        "Violent_sum": 178,
        "Homicide_sum": 0,
        "Rape_sum":0,
        "Robbery_sum":4,
        "AggAssault_sum": 159,
        "PropertyCrime_sum": 269,
        "Burglary_sum": 202,
        "VehicleTheft_sum": 22,
        "LarcenyTheft_sum":166,
        "Arson_sum":4,
    },
    RiversideCounty: {
        "Violent_sum": 7201,
        "Homicide_sum": 111,
        "Rape_sum":2223,
        "Robbery_sum":1607,
        "AggAssault_sum": 4952,
        "PropertyCrime_sum": 50113,
        "Burglary_sum": 20378,
        "VehicleTheft_sum": 10385,
        "LarcenyTheft_sum":31365,
        "Arson_sum":234,
    },
    SacramentoCounty: {
        "Violent_sum": 5034,
        "Homicide_sum": 107,
        "Rape_sum":3159,
        "Robbery_sum":1798,
        "AggAssault_sum": 5573,
        "PropertyCrime_sum": 34457,
        "Burglary_sum": 12745,
        "VehicleTheft_sum": 6306,
        "LarcenyTheft_sum":22796,
        "Arson_sum":317,
    },
    SanBenitoCounty: {
        "Violent_sum": 292,
        "Homicide_sum": 1,
        "Rape_sum":50,
        "Robbery_sum":34,
        "AggAssault_sum": 218,
        "PropertyCrime_sum": 562,
        "Burglary_sum": 268,
        "VehicleTheft_sum": 86,
        "LarcenyTheft_sum":374,
        "Arson_sum":15,
    },
    SanBernardinoCounty: {
        "Violent_sum": 12736,
        "Homicide_sum": 177,
        "Rape_sum":3761,
        "Robbery_sum":2173,
        "AggAssault_sum": 9532,
        "PropertyCrime_sum": 38777,
        "Burglary_sum": 16767,
        "VehicleTheft_sum": 8690,
        "LarcenyTheft_sum":23152,
        "Arson_sum":515,
    },
    SanDiegoCounty: {
        "Violent_sum": 12736,
        "Homicide_sum": 113,
        "Rape_sum":3749,
        "Robbery_sum":2440,
        "AggAssault_sum": 8837,
        "PropertyCrime_sum": 54262,
        "Burglary_sum": 22587,
        "VehicleTheft_sum": 11712,
        "LarcenyTheft_sum":34932,
        "Arson_sum":426,
    },
    SanFranciscoCounty: {
        "Violent_sum": 4996,
        "Homicide_sum": 56,
        "Rape_sum":2811,
        "Robbery_sum":2297,
        "AggAssault_sum": 45265,
        "PropertyCrime_sum": 64153,
        "Burglary_sum": 19074,
        "VehicleTheft_sum": 6091,
        "LarcenyTheft_sum":31861,
        "Arson_sum":380,
    },
    SanJoaquinCounty: {
        "Violent_sum": 5371,
        "Homicide_sum": 63,
        "Rape_sum":1587,
        "Robbery_sum":1046,
        "AggAssault_sum": 3984,
        "PropertyCrime_sum": 17515,
        "Burglary_sum": 6886,
        "VehicleTheft_sum": 2700,
        "LarcenyTheft_sum":4293,
        "Arson_sum":285,
    },
    SanLuisObispoCounty: {
        "Violent_sum": 903,
        "Homicide_sum": 2,
        "Rape_sum":129,
        "Robbery_sum":81,
        "AggAssault_sum": 736,
        "PropertyCrime_sum": 5270,
        "Burglary_sum": 2411,
        "VehicleTheft_sum": 480,
        "LarcenyTheft_sum":3825,
        "Arson_sum":66,
    },
    SanMateoCounty: {
        "Violent_sum": 1687,
        "Homicide_sum": 18,
        "Rape_sum":897,
        "Robbery_sum":522,
        "AggAssault_sum": 855,
        "PropertyCrime_sum": 15291,
        "Burglary_sum": 5497,
        "VehicleTheft_sum": 2320,
        "LarcenyTheft_sum":10752,
        "Arson_sum":99,
    },
    SantaBarbaraCounty: {
        "Violent_sum": 1726,
        "Homicide_sum": 18,
        "Rape_sum":439,
        "Robbery_sum":271,
        "AggAssault_sum": 1216,
        "PropertyCrime_sum": 9642,
        "Burglary_sum": 4493,
        "VehicleTheft_sum": 1800,
        "LarcenyTheft_sum":6055,
        "Arson_sum":79,
    },
    SantaClaraCounty: {
        "Violent_sum": 6800,
        "Homicide_sum": 57,
        "Rape_sum":3125,
        "Robbery_sum":1759,
        "AggAssault_sum": 4004,
        "PropertyCrime_sum": 41997,
        "Burglary_sum": 17382,
        "VehicleTheft_sum": 9136,
        "LarcenyTheft_sum":25671,
        "Arson_sum":459,
    },
    SantaCruzCounty: {
        "Violent_sum": 1052,
        "Homicide_sum": 12,
        "Rape_sum":284,
        "Robbery_sum":192,
        "AggAssault_sum": 735,
        "PropertyCrime_sum": 5478,
        "Burglary_sum": 1944,
        "VehicleTheft_sum": 723,
        "LarcenyTheft_sum":3975,
        "Arson_sum":74,
    },
    ShastaCounty: {
        "Violent_sum": 27,
        "Homicide_sum": 0,
        "Rape_sum":0,
        "Robbery_sum":0,
        "AggAssault_sum": 26,
        "PropertyCrime_sum": 380,
        "Burglary_sum": 40,
        "VehicleTheft_sum": 245,
        "LarcenyTheft_sum":117,
        "Arson_sum":0,
    },
    SierraCounty: {
        "Violent_sum": 6,
        "Homicide_sum": 0,
        "Rape_sum":0,
        "Robbery_sum":0,
        "AggAssault_sum": 6,
        "PropertyCrime_sum": 50,
        "Burglary_sum": 26,
        "VehicleTheft_sum": 11,
        "LarcenyTheft_sum":26,
        "Arson_sum":0,
    },
    SiskiyouCounty: {
        "Violent_sum": 259,
        "Homicide_sum": 4,
        "Rape_sum":27,
        "Robbery_sum":14,
        "AggAssault_sum": 218,
        "PropertyCrime_sum": 704,
        "Burglary_sum": 376,
        "VehicleTheft_sum": 166,
        "LarcenyTheft_sum":388,
        "Arson_sum":0,
    },
    SolanoCounty: {
        "Violent_sum": 2294,
        "Homicide_sum": 32,
        "Rape_sum":928,
        "Robbery_sum":602,
        "AggAssault_sum": 1390,
        "PropertyCrime_sum": 10474,
        "Burglary_sum": 4009,
        "VehicleTheft_sum": 2153,
        "LarcenyTheft_sum":6742,
        "Arson_sum":182,
    },
    
    SonomaCounty: {
        "Violent_sum": 1946,
        "Homicide_sum": 9,
        "Rape_sum":205,
        "Robbery_sum":201,
        "AggAssault_sum": 1434,
        "PropertyCrime_sum": 6707,
        "Burglary_sum": 2331,
        "VehicleTheft_sum": 953,
        "LarcenyTheft_sum":4827,
        "Arson_sum":67,
    },
    StanislausCounty: {
        "Violent_sum": 2740,
        "Homicide_sum": 26,
        "Rape_sum":806,
        "Robbery_sum":503,
        "AggAssault_sum": 2002,
        "PropertyCrime_sum": 10966,
        "Burglary_sum": 3851,
        "VehicleTheft_sum": 1831,
        "LarcenyTheft_sum":7378,
        "Arson_sum":206,
    },

    SutterCounty: {
        "Violent_sum": 414,
        "Homicide_sum": 5,
        "Rape_sum":107,
        "Robbery_sum":65,
        "AggAssault_sum": 305,
        "PropertyCrime_sum": 2355,
        "Burglary_sum": 775,
        "VehicleTheft_sum": 474,
        "LarcenyTheft_sum":509,
        "Arson_sum":17,
    },
    TehamaCounty: {
        "Violent_sum": 355,
        "Homicide_sum": 2,
        "Rape_sum":74,
        "Robbery_sum":47,
        "AggAssault_sum": 232,
        "PropertyCrime_sum": 1289,
        "Burglary_sum": 676,
        "VehicleTheft_sum": 280,
        "LarcenyTheft_sum":730,
        "Arson_sum":44,
    },
    TrinityCounty: {
        "Violent_sum": 83,
        "Homicide_sum": 1,
        "Rape_sum":12,
        "Robbery_sum":7,
        "AggAssault_sum": 70,
        "PropertyCrime_sum": 221,
        "Burglary_sum": 188,
        "VehicleTheft_sum": 36,
        "LarcenyTheft_sum":112,
        "Arson_sum":14,
    },
    TulareCounty: {
        "Violent_sum": 1635,
        "Homicide_sum": 42,
        "Rape_sum":440,
        "Robbery_sum":266,
        "AggAssault_sum": 1403,
        "PropertyCrime_sum": 9082,
        "Burglary_sum": 3692,
        "VehicleTheft_sum": 1919,
        "LarcenyTheft_sum":5737,
        "Arson_sum":68,
    },
    TuolumneCounty: {
        "Violent_sum": 322,
        "Homicide_sum": 1,
        "Rape_sum":32,
        "Robbery_sum":19,
        "AggAssault_sum": 175,
        "PropertyCrime_sum": 951,
        "Burglary_sum": 716,
        "VehicleTheft_sum": 68,
        "LarcenyTheft_sum":221,
        "Arson_sum":7,
    },
    VenturaCounty: {
        "Violent_sum": 1758,
        "Homicide_sum": 20,
        "Rape_sum":679,
        "Robbery_sum":432,
        "AggAssault_sum": 1091,
        "PropertyCrime_sum": 12161,
        "Burglary_sum": 4365,
        "VehicleTheft_sum": 1204,
        "LarcenyTheft_sum":9226,
        "Arson_sum":140,
    },
    YoloCounty: {
        "Violent_sum": 689,
        "Homicide_sum": 5,
        "Rape_sum":424,
        "Robbery_sum":150,
        "AggAssault_sum": 459,
        "PropertyCrime_sum": 503,
        "Burglary_sum": 2133,
        "VehicleTheft_sum": 619,
        "LarcenyTheft_sum":4027,
        "Arson_sum":38,
    },
    YubaCounty: {
        "Violent_sum": 354,
        "Homicide_sum": 6,
        "Rape_sum":117,
        "Robbery_sum":70,
        "AggAssault_sum": 243,
        "PropertyCrime_sum": 1284,
        "Burglary_sum": 547,
        "VehicleTheft_sum": 293,
        "LarcenyTheft_sum":709,
        "Arson_sum":28,
    },
};






















